swagger: "2.0"
info:
  description: "Editor Swagger creado por @EduCCor"
  version: "1.0.0"
  title: "API 1"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8082"
basePath: "/api"
tags:
  - name: "cliente"
    description: "Todo lo necesario para los servicios del Cliente"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
  - name: "linea"
    description: "Acceso a los servicios con Linea Telefonica"
  - name: "oferta"
    description: "Acceso a los servicios con Oferta"
#    externalDocs:
#      description: "Find out more about our store"
#      url: "http://swagger.io"
schemes:
#  - "https"
  - "http"
paths:
  /client/saveClient:
    post:
      tags:
        - "cliente"
      summary: "Agregar un nuevo cliente"
      description: ""
      operationId: "saveClient"
      consumes:
        - "application/json"
      produces:
        - "*/*"
      parameters:
        - in: "body"
          name: "body"
          description: "Formato para el registro de un cliente"
          required: true
          schema:
            $ref: "#/definitions/Cliente"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /client/asociar/{idC}/{idL}:
    post:
      tags:
        - "cliente"
      summary: "Asociar una linea telefonica con un cliente"
      description: ""
      operationId: "joinClientLine"
      consumes:
        - "application/json"
      produces:
        - "*/*"
      parameters:
        - name: "idC"
          in: "path"
          description: "ID del cliente"
          required: true
          type: "integer"
          format: "int64"
        - name: "idL"
          in: "path"
          description: "ID de la linea telefonica"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /client/searchAll:
    get:
      tags:
        - "cliente"
      summary: "Buscar todos los clientes"
      description: "Se encontrara todos los clientes registrados"
      operationId: "getAllClient"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Cliente'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /client/search/{id}:
    get:
      tags:
        - "cliente"
      summary: "Buscar un cliente por su ID"
      description: "regresa un cliente"
      operationId: "getClientById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del cliente a buscar"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Cliente'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Cliente not found
      deprecated: false
  /client/updateClient/{id}:
    put:
      tags:
        - "cliente"
      summary: "Actualizar cliente"
      description: "Actualizar datos del cliente existente"
      operationId: "updateClient"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del cliente a actualizar"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Objeto del cliente para su actualización"
          required: true
          schema:
            $ref: "#/definitions/Cliente"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /client/deleteClient/{id}:
    delete:
      tags:
        - "cliente"
      summary: "Eliminar un cliente sin lineas asociado"
      description: ""
      operationId: "deleteClient"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID del cliente a eliminar"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  /line/addLine:
    post:
      tags:
        - "linea"
      summary: "Agregar una nueva linea telefonica"
      description: ""
      operationId: "addLineClient"
      consumes:
        - "application/json"
      produces:
        - "*/*"
      parameters:
        - in: "body"
          name: "body"
          description: "Formato para el registro de una linea telefonica"
          required: true
          schema:
            $ref: "#/definitions/Linea"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /line/searcLine/{id}:
    get:
      tags:
        - "linea"
      summary: "Buscar una linea telefonica por su ID"
      description: "regresa una linea telefonica"
      operationId: "getLineById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID de la linea telefonica a buscar"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Linea'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Linea Telefonica not found
      deprecated: false
  /line/associar/{idL}/{idO}:
    post:
      tags:
        - "linea"
      summary: "Asociar una oferta con un linea telefonica"
      description: ""
      operationId: "joinLineOferta"
      consumes:
        - "application/json"
      produces:
        - "*/*"
      parameters:
        - name: "idL"
          in: "path"
          description: "ID del cliente"
          required: true
          type: "integer"
          format: "int64"
        - name: "idO"
          in: "path"
          description: "ID de la linea telefonica"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /line/get/{type}/{number}:
    get:
      tags:
        - "linea"
      summary: "Buscar por el Tipo y Numero de Documento Lineas y Ofertas Asociadas al Cliente"
      description: "regresa las lineas y ofertas buscadas"
      operationId: "getReturnLineOfert"
      produces:
          - "application/xml"
          - "application/json"
      parameters:
        - name: "type"
          in: "path"
          description: "Tipo del Documento"
          required: true
          type: "string"
        - name: "number"
          in: "path"
          description: "Numero del Documento"
          required: true
          type: "string"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Linea'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Linea Telefonica y Ofertas not found
      deprecated: false
  /line/changePlan/{id}:
    put:
      tags:
        - "linea"
      summary: "Cambiar plan de una linea telefonica"
      description: ""
      operationId: "getChangePlan"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID de la linea telefonica"
          required: true
          type: "integer"
          format: "int64"
        - in: "body"
          name: "body"
          description: "Formato para el registro de una linea telefonica"
          required: true
          schema:
            $ref: "#/definitions/Linea"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /line/changeState/{id}:
    put:
      tags:
        - "linea"
      summary: "Cambiar estado de una linea telefonica"
      description: ""
      operationId: "getChangeState"
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "id"
          in: "path"
          description: "ID de la linea telefonica"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /oferta/saveOffert:
    post:
      tags:
        - "oferta"
      summary: "Agregar una nueva Oferta"
      description: ""
      operationId: "addOferta"
      consumes:
        - "application/json"
      produces:
        - "*/*"
      parameters:
        - in: "body"
          name: "body"
          description: "Formato para el registro de una oferta"
          required: true
          schema:
            $ref: "#/definitions/Oferta"
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Invalid input
      deprecated: false
  /oferta/searchOferta/{codigoOferta}:
    get:
      tags:
        - "oferta"
      summary: "Buscar una oferta por su Codigo - EhCache"
      description: "regresa una oferta"
      operationId: "getOferta"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "codigoOferta"
          in: "path"
          description: "Codigo de la Oferta"
          required: true
          type: "string"
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Oferta'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Oferta not found
      deprecated: false
  /oferta/allOfertas:
    get:
      tags:
        - "oferta"
      summary: "Buscar todos las ofertas"
      description: "Se encontrara el catalogo de oferta mediante EhCache"
      operationId: "getAllOferta"
      produces:
        - "application/xml"
        - "application/json"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Oferta'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Cliente:
    type: "object"
    required:
      - "name"
      - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: ""
      typeDocument:
        type: "string"
        example: ""
      numberDocument:
        type: "string"
        example: ""
      createClient:
        type: "string"
        example: ""
    xml:
      name: "Cliente"
  Linea:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      nroTelefono:
        type: "string"
        example: ""
      estado:
        type: "string"
        example: ""
      type:
        type: "string"
        example: ""
      nombrePlan:
        type: "string"
        example: ""
    xml:
      name: "Linea"
  Oferta:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      codigoOferta:
        type: "string"
        example: ""
      descripcion:
        type: "string"
        example: ""
      startOferta:
        type: "string"
        example: ""
      endOferta:
        type: "string"
        example: ""
    xml:
      name: "Oferta"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"